### ISSUE TITLE
TFTP isn't running straight out of the box, some bits are missing

### ISSUE THREAD

**Issue by ivang-coder** [bertvv/ansible-role-tftp#10]
Hi folks, thanks for sharing the stuff, was looking for a non-xinetd TFTP for my deployments.

I've been playing with the role on CentOS 7 minimal and "standard" versions, and found it's not running out of box due to some missing bits.

**Issue #1**
The playbook won't run due to missing "policycoreutils-python"
Solution
_../tftp/vars/RedHat.yml_
```
tftp_packages:
  - libsemanage-python
  - policycoreutils-python
  - tftp-server
```
--- end of Issue #1

**Issue #2** 
TFTP won't be accessible due to missing firewalld rule
Solution
_../tftp/handlers/main.yml_
```
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
```

> Alternative handler (tested, less preferable)
```
#- name: restart firewalld
#  command: systemctl restart firewalld
```

> Standard service handler below will cause firewalld to stop on CentOS 7
```
#- name: reload firewalld
#  service:
#    name: firewalld
#    state: reloaded
```

_../tftp/tasks/main.yml_
```
- name: Allow access to TFTP service in firewalld
  firewalld:
    service: tftp
    permanent: yes
    state: enabled
  tags: tftp
  notify:
    - restart firewalld
```
--- end of Issue #2

Cheers,
